@startuml

skinparam class {
  backgroundColor<<mongo>> lightGreen
  backgroundColor<<sql>> lightBlue
  backgroundColor<<redis>> lightPink
  backgroundColor<<neo4j>> lightYellow
}

entity "Customer_" as gCustomers <<mongo>> {
  _id: string
  CustomerID: int
  ---
  Address: string
  City: string
  CompanyName: string
  ContactName: string
  ContactTitle: string
  Country: string
  Fax: string
  Phone: string
  PostalCode: string
  Region: string
  ---
  orders: Order
}

entity "Suppliers" as sSuppliers <<sql>> {
  _id: string
  SupplierID: number
  ---
  Address: string
  City: string
  CompanyName: string
  ContactName: string
  ContactTitle: string
  Country: string
  Fax: string
  HomePage: string
  Phone: string
  PostalCode: string
  Region: string
}

entity "Orders" as gOrders <<mongo>> {
  _id: string
  OrderID: number
  ---
  OrderDate: string
  RequiredDate: string
  ShippedDate: string
  Freight: number
  ShipName: string
  ShipAddress: string
  ShipCity: string
  ShipRegion: string
  ShipPostalCode: string
  ShipCountry: string
  Customer: Customer
  Employee: Employee
  ---
  ShipVia: number
}

entity "Shippers" as nShippers <<neo4j>> {
  Key: Key
  ---
  COMPANYNAME: string
  PHONE: string
}

entity "Order_Details_" as gOrder_Details <<mongo>> {
  OrderRef: int
  ---
  UnitPrice: float
  Quantity: float
  Discount: float
  ---
  ProductRef: int
}

entity "Products" as sProducts <<sql>> {
  ProductID: int
  ---
  ProductName: string
  QuantityPerUnit: string
  UnitPrice: float
  UnitsInStock: int
  UnitsOnOrder: int
  ReorderLevel: int
  Discontinued: bool
  ---
  SupplierRef: int
  CategoryRef: int
}

entity "Categories" as rCategories <<redis>> {
  CategoryID: int
  ---
  CategoryName: string
  Description: string
  Picture: blob
}

entity "Region_" as gRegion <<mongo>> {
  RegionID: int
  ---
  RegionDescription: string
}
entity "Territory_" as gTerritory <<mongo>> {
  TerritoryID: string
  Region: Region
  ---
  TerritoryDescription: string

}

entity "Employees" as gEmployees <<mongo>> {
  EmployeeID: int
  ---
  LastName: string
  FirstName: string
  Title: string
  TitleOfCourtesy: string
  BirthDate: datetime
  HireDate: datetime
  Address: string
  City: string
  Region: string
  PostalCode: string
  Country: string
  HomePhone: string
  Extension: string
  Photo: blob
  Notes: string
  PhotoPath: string
  Salary: float
  Territory: Territory
  ---
  ReportsTo: int
}


gEmployees ||-l-|| gTerritory : contains_
gTerritory||-u-|| gRegion  : contains_
gOrder_Details |o--|| sProducts : details
gOrder_Details }o--|| gOrders : details
gEmployees }o--|| gEmployees : reportTo
sProducts }o-d-|| rCategories : belongs
sProducts |o-r-|| sSuppliers : supply
gOrders }o-r-|| nShippers : via
gOrders ||-u-|| gCustomers : for
gOrders ||--|| gEmployees : by
nShippers }o-l-o{ nShippers: related
' rOrders = gOrder_
' rOrders = sOrders

@enduml
